InstantCredit/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using InstantCredit.Models;
using InstantCredit.Models.Enums;
using InstantCredit.ViewModels;
using InstantCredit.Core;

namespace InstantCredit.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly InstantCreditContext db;
        private readonly FileService fileService;

        public ApplicationController(InstantCreditContext context)
        {
            db = context;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            User user = await db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);

            List<CreditApplication> creditApplications;

            if (user.isAdmin)
            {
                creditApplications = db.CreditApplications
                    .Where(application => application.Status == ApplicationStatus.NotViewed || application.Status == ApplicationStatus.Approved)
                    .ToList();
            }
            else
            {
                creditApplications = db.CreditApplications
                        .Where(application => 
                            application.User.Email == User.Identity.Name &&
                            application.Status != ApplicationStatus.Done)
                        .ToList();
            }

            return View(creditApplications);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            User user = await db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);
            if (!user.isAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateApplicationModel model)
        {
            User user = await db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);+
            if (!user.isAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                var creditPlan = await db.CreditPlans.FirstOrDefaultAsync(c => c.Id == model.CreditPlan);

                db.CreditApplications.Add(new CreditApplication
                {
                    PassportFile = await fileService.SavePassportFileAsync(model.PassportFile),
                    IncomeStatementFile = await fileService.SaveIncomeStatmentAsync(model.IncomeStatementFile),
                    ContactPhone = model.ContactPhone,
                    CreditPlan = creditPlan,
                    User = user
                }); ;
                await db.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }
    }
}

InstantCredit/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InstantCredit.Models;
using InstantCredit.Models.Enums;
using InstantCredit.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InstantCredit.Controllers
{
    public class HomeController : Controller
    {
        private readonly InstantCreditContext db;

        public HomeController(InstantCreditContext context)
        {
            db = context;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);

            var creditPlans = db.CreditPlans
                .Where(plan => plan.Status == CreditPlanStatus.Active)
                .ToList();

            return View(new CreditPlansModel() { IsAdmin = user.isAdmin, CreditPlans = creditPlans });
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var user = await db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);
            if (!user.isAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateCreditPlanModel model)
        {
            var user = await db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);
            if (!user.isAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                db.CreditPlans.Add(new CreditPlan 
                {
                    Name = model.Name,
                    Period = model.Period,
                    Percents = model.Percents,
                    Description = model.Description
                });
                await db.SaveChangesAsync();
                
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Deactivate(int id)
        {
            var user = await db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);
            if (user.isAdmin)
            {
                var plan = await db.CreditPlans.FirstOrDefaultAsync(plan => plan.Id == id);
                plan.Status = CreditPlanStatus.Disabled;
                await db.SaveChangesAsync();
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

InstantCredit/Views/Home/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model InstantCredit.ViewModels.CreateCreditPlanModel

@{
    Layout = "~/Views/Shared/Layout.cshtml";
}


<form class="form-horizontal" asp-action="Create" asp-controller="Home" method="POST">
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <div>
        <div class="form-group">
            <label asp-for="Name">Name:</label>
            <input asp-for="Name" type="email"
                   class="form-control"
                   required="required"
                   placeholder="Enter credit plan name">
            <span asp-validation-for="Name" />
        </div>
        <div class="form-group">
            <label asp-for="Period">Period in monthes:</label>
            <input asp-for="Period"
                   type="number"
                   class="form-control"
                   required="required"
                   placeholder="Enter credital period">
            <span asp-validation-for="Period" />
        </div>
        <div class="form-group">
            <label asp-for="Percents">Percentage:</label>
            <input asp-for="Percents"
                   type="number"
                   class="form-control"
                   required="required"
                   placeholder="Enter percentage">
            <span asp-validation-for="Percents" />
        </div>
        <div class="form-group">
            <label asp-for="Description">Description:</label>
            <textarea asp-for="Description"
                   class="form-control"
                   required="required"
                   placeholder="Enter description">
            </textarea>
            <span asp-validation-for="Description" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

InstantCredit/Views/Home/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model InstantCredit.ViewModels.CreditPlansModel

@{
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="container">
    @if (Model.IsAdmin)
    {
        <div class="p-2">
            <a class="dropdown-item" asp-action="Create" asp-controller="Home">Create Credit Plan</a>
        </div>
    }
    else
    {
        <div class="p-2">
            <a class="dropdown-item" asp-action="Create" asp-controller="Application">Apply For Plan</a>
        </div>
    }

    <div class="list-group">
        @foreach (var plan in Model.CreditPlans)
        {
            <div class="list-group-item d-flex justify-content-between bg-light mb-3">
                <div class="p-2">
                    <div>Name: @plan.Name</div>
                    <div>Month: @plan.Period</div>
                    <div>Percentage: @plan.Percents</div>
                    <div>Description: @plan.Description</div>
                    @if (Model.IsAdmin)
                    { 
                        <a asp-action="Deactivate" asp-controller="Home" asp-route-id=@plan.Id>Deactivate Plan</a>
                    }
                </div>
            </div>
        }
    </div>
</div>